# Generated by Django 4.1 on 2022-11-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sessions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("20 minutes", "20 minutes"),
                            ("30 minutes", "30 minutes"),
                            ("45 minutes", "45 minutes"),
                            ("60 minutes", "60 minutes"),
                            ("75 minutes", "75 minutes"),
                            ("90 minutes", "90 minutes"),
                        ],
                        max_length=100,
                    ),
                ),
                ("exercise1", models.CharField(max_length=100)),
                ("exercise2", models.CharField(max_length=100)),
                ("exercise3", models.CharField(max_length=100)),
            ],
            options={"verbose_name_plural": "Sessions",},
        ),
    ]
